---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - namespace.yaml
  - elasticsearch.yaml
  - fluentd-rbac.yaml
  - fluentd.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: fluentd-config
    files:
      - fluent.conf=fluentd/fluent.conf
      - index-template.json=fluentd/index-template.json
generatorOptions:
  labels:
    app.kubernetes.io/name: fluentd
