---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - deployments.yaml
  - services.yaml
  - httproutes.yaml
  - reliability.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: web-nginx-template
    files:
      - default.conf.template=nginx/default.conf.template
generatorOptions:
  labels:
    app.kubernetes.io/name: web
