---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: demo-platform
    # разрешает HTTPRoute из этого namespace присоединяться к Gateway
    gateway-access: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
