---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-v1
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/version: v1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-v1
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
